#!/usr/bin/env bash
# @version: 3.4.0
# UserPromptSubmit — minimal latency mode.
# No file discovery, no scoring, no aliases, no snippets.
# Handles: --y flag, intent detection, project profile read, file index cache, command hint.

source "${CORTEX_ROOT:-$(pwd)/.claude}/core/shared/bootstrap.sh" || exit 0

input=$(cat)
[[ -z "$input" ]] && exit 0

prompt=$(echo "$input" | jq -r '.prompt // empty' 2>/dev/null)
[[ -z "$prompt" ]] && exit 0

# ── --y flag ──────────────────────────────────────────────────────────────────
yes_mode=0
if [[ "$prompt" =~ (^|[[:space:]])--y([[:space:]]|$) || "$prompt" == *" --y" || "$prompt" == "--y" ]]; then
  yes_mode=1
  prompt=$(sed -e 's/[[:space:]]*--y[[:space:]]*$//' -e 's/[[:space:]]*--y[[:space:]]/ /g' <<< "$prompt" | xargs)
fi

# Fast-path: no enrichment needed for standard prompts
[[ $yes_mode -eq 0 ]] && exit 0

# ── File index cache ──────────────────────────────────────────────────────────
FILE_INDEX="$CORTEX_CACHE/project-file-index.txt"
file_count=""
if [[ -f "$FILE_INDEX" && -s "$FILE_INDEX" ]]; then
  file_count=$(wc -l < "$FILE_INDEX" 2>/dev/null | tr -d ' ')
else
  echo "[CORTEX] File index missing — run /init-cortex to rebuild file index cache" >&2
fi

# ── Intent detection (lightweight) ───────────────────────────────────────────
prompt_lower=$(echo "$prompt" | tr '[:upper:]' '[:lower:]')
intent="question"
if grep -qE '\b(fix|bug|error|issue|broken|crash|fail|exception)\b' <<< "$prompt_lower"; then
  intent="bug_fix"
elif grep -qE '\b(add|implement|create|build|new feature|write)\b' <<< "$prompt_lower"; then
  intent="feature_request"
elif grep -qE '\b(refactor|clean up|optimize|simplify|restructure)\b' <<< "$prompt_lower"; then
  intent="refactor"
fi

# ── Project profile (single jq read, already generated by session-start.sh) ──
PROFILE="$CORTEX_CACHE/project-profile.json"
project_type="unknown"; framework=""; arch=""
if [[ -f "$PROFILE" ]] && jq empty "$PROFILE" 2>/dev/null; then
  project_type=$(jq -r '.project_type // "unknown"' "$PROFILE" 2>/dev/null)
  framework=$(jq    -r '.framework    // empty'     "$PROFILE" 2>/dev/null)
  arch=$(jq         -r '.arch         // empty'     "$PROFILE" 2>/dev/null)
fi

# ── Build enriched prompt ─────────────────────────────────────────────────────
ctx="[CORTEX]
intent: ${intent}
project: ${project_type}"
[[ -n "$framework" ]]  && ctx="${ctx}"$'\n'"framework: ${framework}"
[[ -n "$arch" ]]       && ctx="${ctx}"$'\n'"arch: ${arch}"
[[ -n "$file_count" ]] && ctx="${ctx}"$'\n'"files: ${file_count}"
ctx="${ctx}"$'\n'"[/CORTEX]"

enriched="${ctx}"$'\n\n'"${prompt}"$'\n\n'"[GLOBAL ANSWER POLICY]
Default all binary decisions to YES. Skip confirmation prompts for non-destructive operations. Proceed directly with the requested action. Security risks and destructive operations (rm -rf, DROP TABLE, force-push to main) remain protected."

jq -n --arg p "$enriched" '{"prompt": $p}'
exit 0
